name: Setup BendSQL
description: setup bendsql for perf test

runs:
  using: composite
  steps:
    - name: Get BendSQL from release
      shell: bash
      run: |
        sudo curl -L -o /usr/share/keyrings/datafuselabs-keyring.gpg https://repo.databend.rs/deb/datafuselabs.gpg
        sudo curl -L -o /etc/apt/sources.list.d/datafuselabs.list https://repo.databend.rs/deb/datafuselabs.list
        sudo apt update
        sudo apt install -y bendsql
        bendsql --version
