name: Setup bendsql
description: setup bendsql for perf test
inputs:
  email:
    required: true
    description: ""
  password:
    required: true
    description: ""
  org:
    required: true
    description: ""

runs:
  using: composite
  steps:
    - name: Get bendsql from repo
      shell: bash
      run: |
        curl -fsSLo ./bendsql.tar.gz https://github.com/databendcloud/bendsql/releases/download/v0.1.2/bendsql-linux-amd64.tar.gz
        tar -xvzf ./bendsql.tar.gz
        chmod +x ./linux-amd64/bendsql
        sudo cp ./linux-amd64/bendsql /usr/bin/bendsql

    - name: bendsql login
      shell: bash
      env:
        BENDSQL_API_ENDPOINT: https://webapi-dev.datafusecloud.com/
      run: |
        bendsql cloud login --email=${{ inputs.email }} --password=${{ inputs.password }} --org=${{ inputs.org }}
        bendsql cloud warehouse ls
