name: Reload data
description: reload test data for perf test
inputs:
  dsn:
    required: true
    description: ""
  script:
    required: true
    description: ""
  warehouse:
    required: true
    description: ""
  aws_key_id:
    required: true
    description: ""
  aws_secret_key:
    required: true
    description: ""
  feishu_webhook_url:
    required: true
    description: ""

runs:
  using: composite
  steps:
    - name: setup bendsql
      uses: ./.github/actions/setup-bendsql

    - name: Ensure warehouse
      env:
        BENDSQL_DSN: ${{ inputs.dsn }}
      shell: bash
      run: |
        echo "SHOW WAREHOUSES;" | bendsql
        echo "CREATE WAREHOUSE IF NOT EXISTS '${{ inputs.warehouse }}' WITH WAREHOUSE_SIZE = 'SMALL';" | bendsql
        echo "SHOW WAREHOUSES;" | bendsql
        echo "BENDSQL_DSN=${BENDSQL_DSN}&warehouse=${{ inputs.warehouse }}" >> $GITHUB_ENV

    - name: Get start time
      shell: bash
      run: |
        echo "START_TIME=$(date +%s)" >> GITHUB_ENV

    - name: Run reload script
      shell: bash
      run: |
        bash -e ${{ inputs.script }}
      env:
        AWS_KEY_ID: ${{ inputs.aws_key_id }}
        AWS_SECRET_KEY: ${{ inputs.aws_secret_key }}

    - name: Get time elapsed
      if: ${{ always() }}
      shell: bash
      run: |
        echo "ELAPSED_SECONDS=$(expr $(date +%s) - $START_TIME)" >> GITHUB_ENV

    - name: Notify Feishu Group
      uses: foxundermoon/feishu-action@v2
      if: ${{ always() }}
      with:
        url: ${{ inputs.feishu_webhook_url }}
        msg_type: post
        content: |
          post:
            zh_cn:
              title: Reload ${{ inputs.script }} ${{ github.action_status }} (${{ env.ELAPSED_SECONDS }})
              content:
              - [{"tag": "a", "text": "link", "href": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]
