name: Reload data
description: reload test data for perf test
inputs:
  email:
    required: true
    description: ""
  password:
    required: true
    description: ""
  org:
    required: true
    description: ""
  script:
    required: true
    description: ""
  warehouse:
    required: true
    description: ""
  aws_key_id:
    required: true
    description: ""
  aws_secret_key:
    required: true
    description: ""
  feishu_webhook_url:
    required: true
    description: ""

runs:
  using: composite
  steps:
    - name: setup bendsql
      uses: ./.github/actions/setup-bendsql
      with:
        email: ${{ inputs.email }}
        password: ${{ inputs.password }}
        org: ${{ inputs.org }}

    - name: Ensure warehouse
      shell: bash
      run: |
        bendsql cloud warehouse create ${{ inputs.warehouse }} --size=Small
        bendsql cloud warehouse use ${{ inputs.warehouse }}

    - name: Run reload script
      shell: bash
      run: |
        bash -e ${{ inputs.script }}
      env:
        AWS_KEY_ID: ${{ inputs.aws_key_id }}
        AWS_SECRET_KEY: ${{ inputs.aws_secret_key }}

    - name: Notify Feishu Group
      uses: foxundermoon/feishu-action@v2
      if: ${{ always() }}
      with:
        url: ${{ inputs.feishu_webhook_url }}
        msg_type: post
        content: |
          post:
            zh_cn:
              title: Reload ${{ inputs.script }} ${{ github.action_status }}
              content:
              - [{"tag": "a", "text": "link", "href": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]
